name: Deploy application

on:
  push:
    tags: 'v*'

jobs:
  deploy:
    name: Deploy to Shuttle
    runs-on: ubuntu-latest
    steps:
      - name: Deploy application
        uses: shuttle-hq/deploy-action@main
        with:
          deploy-key: ${{ secrets.SHUTTLE_API_KEY }}
          name: 'ebsi-rs'
          secrets: |
            DISCORD_TOKEN = ${{ secrets.DISCORD_TOKEN }}
