name: Test application

on:
  push:
    branches-ignore:
      - 'main'
      - 'ci'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    name: Test project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - name: Run checks
        run: cargo check --verbose
      - name: Test project
        run: cargo test --all --all-features --verbose
