name: Build and test application

on:
  push:
    branches-ignore:
      - 'main'
      - 'ci'
  pull_request:
    branches:
      - 'main'

env:
  SCCACHE_GHA_ENABLED: 'true'
  RUSTC_WRAPPER: 'sccache'
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and cache project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: mozilla-actions/sccache-action@v0.0.3
      - name: Build project
        run: cargo build --verbose
  
  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Restore cache
        uses: mozilla-actions/sccache-action@v0.0.3
      - name: Test project
        run: cargo test --all --all-features --verbose
      